#!/bin/bash
# Berbagive Deployment Script
set -e

echo "=== Berbagive Deployment ==="

command -v docker >/dev/null 2>&1 || { echo "Docker is required but not installed."; exit 1; }
command -v docker compose >/dev/null 2>&1 || { echo "Docker Compose is required but not installed."; exit 1; }

# --- Prepare .env from template if not exists ---
if [ ! -f .env ]; then
    echo "Creating .env from .env.docker template..."
    cp .env.docker .env
    echo ""
    echo "============================================================"
    echo "  IMPORTANT: Edit .env before re-running deploy.sh!"
    echo "  - Set strong passwords for DB_PASSWORD and MINIO_ROOT_PASSWORD"
    echo "  - APP_KEY will be auto-generated by this script"
    echo "============================================================"
    exit 0
fi

# --- Validate required env vars ---
if [ -z "${DB_PASSWORD}" ] || [ "${DB_PASSWORD}" = "changeme" ]; then
    echo "ERROR: DB_PASSWORD is empty or still set to default. Set it in .env first."
    exit 1
fi
if [ -z "${MINIO_ROOT_PASSWORD}" ] || [ "${MINIO_ROOT_PASSWORD}" = "changeme" ]; then
    echo "ERROR: MINIO_ROOT_PASSWORD is empty or still set to default. Set it in .env first."
    exit 1
fi

set -a; source .env; set +a

# --- Build frontend with production API URL ---
echo "Building frontend..."
cp -f frontend/.env.production frontend/.env
if [ ! -d frontend/node_modules ]; then
    (cd frontend && npm install)
fi
(cd frontend && npm run build)

# --- Build Docker images ---
echo "Building Docker images..."
docker compose build --pull

# --- Start all services ---
echo "Starting containers..."
docker compose up -d

# --- Wait for database ---
echo "Waiting for database..."
sleep 5
for i in $(seq 1 30); do
    if docker compose exec -T db pg_isready -U "${DB_USERNAME:-berbagive}" -d "${DB_DATABASE:-berbagive}" 2>/dev/null; then
        break
    fi
    echo "  waiting... ($i)"
    sleep 2
done

# --- Run Laravel setup ---
echo "Running Laravel setup..."
docker compose exec -T app php artisan key:generate --force
docker compose exec -T app php artisan package:discover --ansi
docker compose exec -T app php artisan storage:link 2>/dev/null || true

# --- Create MinIO bucket ---
echo "Creating MinIO bucket..."
docker compose exec -T minio mc alias set local http://localhost:9000 "${MINIO_ROOT_USER:-berbagive}" "${MINIO_ROOT_PASSWORD:-berbagive123}" 2>/dev/null || true
docker compose exec -T minio mc mb local/berbagive --ignore-existing 2>/dev/null || true
docker compose exec -T minio mc anonymous set public local/berbagive 2>/dev/null || true

echo ""
echo "====================================================================="
echo "  Docker containers running. DB is EMPTY - waiting for DDL + data."
echo ""
echo "  Run DDL files (remove CREATE DATABASE from ddl first):"
echo "    docker compose exec -T db psql -U ${DB_USERNAME:-berbagive} -d ${DB_DATABASE:-berbagive} < ddl/rsi-mandat-ddl.sql"
echo "    docker compose exec -T db psql -U ${DB_USERNAME:-berbagive} -d ${DB_DATABASE:-berbagive} < ddl/rsi-mandat-constraint.sql"
echo "    docker compose exec -T db psql -U ${DB_USERNAME:-berbagive} -d ${DB_DATABASE:-berbagive} < ddl/rsi-mandat-view.sql"
echo "    docker compose exec -T db psql -U ${DB_USERNAME:-berbagive} -d ${DB_DATABASE:-berbagive} < ddl/rsi-mandat-sp.sql"
echo "    docker compose exec -T db psql -U ${DB_USERNAME:-berbagive} -d ${DB_DATABASE:-berbagive} < ddl/rsi-mandat-fn.sql"
echo "    docker compose exec -T db psql -U ${DB_USERNAME:-berbagive} -d ${DB_DATABASE:-berbagive} < ddl/rsi-mandat-index.sql"
echo ""
echo "  After data inserted, run: ./finalize.sh"
echo ""
echo "  Tailscale Funnel (akses publik):"
echo "    sudo tailscale funnel --bg http://localhost:${HTTP_PORT:-8080}"
echo "    tailscale serve status"
echo "====================================================================="
echo ""
echo "Application: http://localhost:${HTTP_PORT:-80}"
echo "MinIO Console: http://localhost:9001"
echo "Health:      http://localhost:${HTTP_PORT:-80}/api/v1/health"
