# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitoring.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10monitoring.proto\x12\nmonitoring\"0\n\x19\x43\x61mpaignMonitoringRequest\x12\x13\n\x0bid_campaign\x18\x01 \x01(\x05\"@\n\x0b\x44onaturItem\x12\x0c\n\x04nama\x18\x01 \x01(\t\x12\x12\n\ncreated_at\x18\x02 \x01(\t\x12\x0f\n\x07nominal\x18\x03 \x01(\x03\"\xd1\x02\n\x18\x43\x61mpaignMonitoringUpdate\x12\x13\n\x0bid_campaign\x18\x01 \x01(\x05\x12\r\n\x05judul\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x14\n\x0cnama_lembaga\x18\x04 \x01(\t\x12\x15\n\rnama_kategori\x18\x05 \x01(\t\x12\x13\n\x0btarget_dana\x18\x06 \x01(\x03\x12\x16\n\x0e\x64\x61na_terkumpul\x18\x07 \x01(\x03\x12\x17\n\x0fprogress_persen\x18\x08 \x01(\x02\x12\x16\n\x0ejumlah_donatur\x18\t \x01(\x05\x12\x14\n\x0chari_tersisa\x18\n \x01(\x05\x12\x15\n\rtanggal_mulai\x18\x0b \x01(\t\x12\x17\n\x0ftanggal_selesai\x18\x0c \x01(\t\x12\x30\n\x0f\x64onatur_terbaru\x18\r \x03(\x0b\x32\x17.monitoring.DonaturItem2\xec\x01\n\x19\x43\x61mpaignMonitoringService\x12\x64\n\x15GetCampaignMonitoring\x12%.monitoring.CampaignMonitoringRequest\x1a$.monitoring.CampaignMonitoringUpdate\x12i\n\x18StreamCampaignMonitoring\x12%.monitoring.CampaignMonitoringRequest\x1a$.monitoring.CampaignMonitoringUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMPAIGNMONITORINGREQUEST']._serialized_start=32
  _globals['_CAMPAIGNMONITORINGREQUEST']._serialized_end=80
  _globals['_DONATURITEM']._serialized_start=82
  _globals['_DONATURITEM']._serialized_end=146
  _globals['_CAMPAIGNMONITORINGUPDATE']._serialized_start=149
  _globals['_CAMPAIGNMONITORINGUPDATE']._serialized_end=486
  _globals['_CAMPAIGNMONITORINGSERVICE']._serialized_start=489
  _globals['_CAMPAIGNMONITORINGSERVICE']._serialized_end=725
# @@protoc_insertion_point(module_scope)
