// source: monitoring.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = globalThis;

goog.exportSymbol('proto.monitoring.CampaignMonitoringRequest', null, global);
goog.exportSymbol('proto.monitoring.CampaignMonitoringUpdate', null, global);
goog.exportSymbol('proto.monitoring.DonaturItem', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.monitoring.CampaignMonitoringRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.monitoring.CampaignMonitoringRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.monitoring.CampaignMonitoringRequest.displayName = 'proto.monitoring.CampaignMonitoringRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.monitoring.DonaturItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.monitoring.DonaturItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.monitoring.DonaturItem.displayName = 'proto.monitoring.DonaturItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.monitoring.CampaignMonitoringUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.monitoring.CampaignMonitoringUpdate.repeatedFields_, null);
};
goog.inherits(proto.monitoring.CampaignMonitoringUpdate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.monitoring.CampaignMonitoringUpdate.displayName = 'proto.monitoring.CampaignMonitoringUpdate';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.monitoring.CampaignMonitoringRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.monitoring.CampaignMonitoringRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.monitoring.CampaignMonitoringRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.monitoring.CampaignMonitoringRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
idCampaign: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.monitoring.CampaignMonitoringRequest}
 */
proto.monitoring.CampaignMonitoringRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.monitoring.CampaignMonitoringRequest;
  return proto.monitoring.CampaignMonitoringRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.monitoring.CampaignMonitoringRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.monitoring.CampaignMonitoringRequest}
 */
proto.monitoring.CampaignMonitoringRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIdCampaign(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.monitoring.CampaignMonitoringRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.monitoring.CampaignMonitoringRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.monitoring.CampaignMonitoringRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.monitoring.CampaignMonitoringRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdCampaign();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 id_campaign = 1;
 * @return {number}
 */
proto.monitoring.CampaignMonitoringRequest.prototype.getIdCampaign = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.monitoring.CampaignMonitoringRequest} returns this
 */
proto.monitoring.CampaignMonitoringRequest.prototype.setIdCampaign = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.monitoring.DonaturItem.prototype.toObject = function(opt_includeInstance) {
  return proto.monitoring.DonaturItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.monitoring.DonaturItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.monitoring.DonaturItem.toObject = function(includeInstance, msg) {
  var f, obj = {
nama: jspb.Message.getFieldWithDefault(msg, 1, ""),
createdAt: jspb.Message.getFieldWithDefault(msg, 2, ""),
nominal: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.monitoring.DonaturItem}
 */
proto.monitoring.DonaturItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.monitoring.DonaturItem;
  return proto.monitoring.DonaturItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.monitoring.DonaturItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.monitoring.DonaturItem}
 */
proto.monitoring.DonaturItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setNama(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNominal(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.monitoring.DonaturItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.monitoring.DonaturItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.monitoring.DonaturItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.monitoring.DonaturItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNama();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCreatedAt();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getNominal();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional string nama = 1;
 * @return {string}
 */
proto.monitoring.DonaturItem.prototype.getNama = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.monitoring.DonaturItem} returns this
 */
proto.monitoring.DonaturItem.prototype.setNama = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string created_at = 2;
 * @return {string}
 */
proto.monitoring.DonaturItem.prototype.getCreatedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.monitoring.DonaturItem} returns this
 */
proto.monitoring.DonaturItem.prototype.setCreatedAt = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 nominal = 3;
 * @return {number}
 */
proto.monitoring.DonaturItem.prototype.getNominal = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.monitoring.DonaturItem} returns this
 */
proto.monitoring.DonaturItem.prototype.setNominal = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.monitoring.CampaignMonitoringUpdate.repeatedFields_ = [13];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.monitoring.CampaignMonitoringUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.monitoring.CampaignMonitoringUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.monitoring.CampaignMonitoringUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
idCampaign: jspb.Message.getFieldWithDefault(msg, 1, 0),
judul: jspb.Message.getFieldWithDefault(msg, 2, ""),
status: jspb.Message.getFieldWithDefault(msg, 3, ""),
namaLembaga: jspb.Message.getFieldWithDefault(msg, 4, ""),
namaKategori: jspb.Message.getFieldWithDefault(msg, 5, ""),
targetDana: jspb.Message.getFieldWithDefault(msg, 6, 0),
danaTerkumpul: jspb.Message.getFieldWithDefault(msg, 7, 0),
progressPersen: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
jumlahDonatur: jspb.Message.getFieldWithDefault(msg, 9, 0),
hariTersisa: jspb.Message.getFieldWithDefault(msg, 10, 0),
tanggalMulai: jspb.Message.getFieldWithDefault(msg, 11, ""),
tanggalSelesai: jspb.Message.getFieldWithDefault(msg, 12, ""),
donaturTerbaruList: jspb.Message.toObjectList(msg.getDonaturTerbaruList(),
    proto.monitoring.DonaturItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.monitoring.CampaignMonitoringUpdate}
 */
proto.monitoring.CampaignMonitoringUpdate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.monitoring.CampaignMonitoringUpdate;
  return proto.monitoring.CampaignMonitoringUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.monitoring.CampaignMonitoringUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.monitoring.CampaignMonitoringUpdate}
 */
proto.monitoring.CampaignMonitoringUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIdCampaign(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setJudul(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setStatus(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setNamaLembaga(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setNamaKategori(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTargetDana(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDanaTerkumpul(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setProgressPersen(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setJumlahDonatur(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHariTersisa(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setTanggalMulai(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setTanggalSelesai(value);
      break;
    case 13:
      var value = new proto.monitoring.DonaturItem;
      reader.readMessage(value,proto.monitoring.DonaturItem.deserializeBinaryFromReader);
      msg.addDonaturTerbaru(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.monitoring.CampaignMonitoringUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.monitoring.CampaignMonitoringUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.monitoring.CampaignMonitoringUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdCampaign();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getJudul();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNamaLembaga();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getNamaKategori();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTargetDana();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getDanaTerkumpul();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getProgressPersen();
  if (f !== 0.0) {
    writer.writeFloat(
      8,
      f
    );
  }
  f = message.getJumlahDonatur();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getHariTersisa();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getTanggalMulai();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getTanggalSelesai();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getDonaturTerbaruList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      proto.monitoring.DonaturItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 id_campaign = 1;
 * @return {number}
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.getIdCampaign = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.monitoring.CampaignMonitoringUpdate} returns this
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.setIdCampaign = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string judul = 2;
 * @return {string}
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.getJudul = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.monitoring.CampaignMonitoringUpdate} returns this
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.setJudul = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string status = 3;
 * @return {string}
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.monitoring.CampaignMonitoringUpdate} returns this
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string nama_lembaga = 4;
 * @return {string}
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.getNamaLembaga = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.monitoring.CampaignMonitoringUpdate} returns this
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.setNamaLembaga = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string nama_kategori = 5;
 * @return {string}
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.getNamaKategori = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.monitoring.CampaignMonitoringUpdate} returns this
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.setNamaKategori = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int64 target_dana = 6;
 * @return {number}
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.getTargetDana = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.monitoring.CampaignMonitoringUpdate} returns this
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.setTargetDana = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int64 dana_terkumpul = 7;
 * @return {number}
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.getDanaTerkumpul = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.monitoring.CampaignMonitoringUpdate} returns this
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.setDanaTerkumpul = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional float progress_persen = 8;
 * @return {number}
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.getProgressPersen = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitoring.CampaignMonitoringUpdate} returns this
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.setProgressPersen = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional int32 jumlah_donatur = 9;
 * @return {number}
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.getJumlahDonatur = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.monitoring.CampaignMonitoringUpdate} returns this
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.setJumlahDonatur = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 hari_tersisa = 10;
 * @return {number}
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.getHariTersisa = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.monitoring.CampaignMonitoringUpdate} returns this
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.setHariTersisa = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional string tanggal_mulai = 11;
 * @return {string}
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.getTanggalMulai = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.monitoring.CampaignMonitoringUpdate} returns this
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.setTanggalMulai = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string tanggal_selesai = 12;
 * @return {string}
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.getTanggalSelesai = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.monitoring.CampaignMonitoringUpdate} returns this
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.setTanggalSelesai = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * repeated DonaturItem donatur_terbaru = 13;
 * @return {!Array<!proto.monitoring.DonaturItem>}
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.getDonaturTerbaruList = function() {
  return /** @type{!Array<!proto.monitoring.DonaturItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.monitoring.DonaturItem, 13));
};


/**
 * @param {!Array<!proto.monitoring.DonaturItem>} value
 * @return {!proto.monitoring.CampaignMonitoringUpdate} returns this
*/
proto.monitoring.CampaignMonitoringUpdate.prototype.setDonaturTerbaruList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.monitoring.DonaturItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.monitoring.DonaturItem}
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.addDonaturTerbaru = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.monitoring.DonaturItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.monitoring.CampaignMonitoringUpdate} returns this
 */
proto.monitoring.CampaignMonitoringUpdate.prototype.clearDonaturTerbaruList = function() {
  return this.setDonaturTerbaruList([]);
};


goog.object.extend(exports, proto.monitoring);
