/**
 * @fileoverview gRPC-Web generated client stub for monitoring
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.1.1
// 	protoc              v7.36.1
// source: monitoring.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.monitoring = require('./monitoring_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.monitoring.CampaignMonitoringServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.monitoring.CampaignMonitoringServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.monitoring.CampaignMonitoringRequest,
 *   !proto.monitoring.CampaignMonitoringUpdate>}
 */
const methodDescriptor_CampaignMonitoringService_GetCampaignMonitoring = new grpc.web.MethodDescriptor(
  '/monitoring.CampaignMonitoringService/GetCampaignMonitoring',
  grpc.web.MethodType.UNARY,
  proto.monitoring.CampaignMonitoringRequest,
  proto.monitoring.CampaignMonitoringUpdate,
  /**
   * @param {!proto.monitoring.CampaignMonitoringRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.monitoring.CampaignMonitoringUpdate.deserializeBinary
);


/**
 * @param {!proto.monitoring.CampaignMonitoringRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.monitoring.CampaignMonitoringUpdate)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.monitoring.CampaignMonitoringUpdate>|undefined}
 *     The XHR Node Readable Stream
 */
proto.monitoring.CampaignMonitoringServiceClient.prototype.getCampaignMonitoring =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/monitoring.CampaignMonitoringService/GetCampaignMonitoring',
      request,
      metadata || {},
      methodDescriptor_CampaignMonitoringService_GetCampaignMonitoring,
      callback);
};


/**
 * @param {!proto.monitoring.CampaignMonitoringRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.monitoring.CampaignMonitoringUpdate>}
 *     Promise that resolves to the response
 */
proto.monitoring.CampaignMonitoringServicePromiseClient.prototype.getCampaignMonitoring =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/monitoring.CampaignMonitoringService/GetCampaignMonitoring',
      request,
      metadata || {},
      methodDescriptor_CampaignMonitoringService_GetCampaignMonitoring);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.monitoring.CampaignMonitoringRequest,
 *   !proto.monitoring.CampaignMonitoringUpdate>}
 */
const methodDescriptor_CampaignMonitoringService_StreamCampaignMonitoring = new grpc.web.MethodDescriptor(
  '/monitoring.CampaignMonitoringService/StreamCampaignMonitoring',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.monitoring.CampaignMonitoringRequest,
  proto.monitoring.CampaignMonitoringUpdate,
  /**
   * @param {!proto.monitoring.CampaignMonitoringRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.monitoring.CampaignMonitoringUpdate.deserializeBinary
);


/**
 * @param {!proto.monitoring.CampaignMonitoringRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.monitoring.CampaignMonitoringUpdate>}
 *     The XHR Node Readable Stream
 */
proto.monitoring.CampaignMonitoringServiceClient.prototype.streamCampaignMonitoring =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/monitoring.CampaignMonitoringService/StreamCampaignMonitoring',
      request,
      metadata || {},
      methodDescriptor_CampaignMonitoringService_StreamCampaignMonitoring);
};


/**
 * @param {!proto.monitoring.CampaignMonitoringRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.monitoring.CampaignMonitoringUpdate>}
 *     The XHR Node Readable Stream
 */
proto.monitoring.CampaignMonitoringServicePromiseClient.prototype.streamCampaignMonitoring =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/monitoring.CampaignMonitoringService/StreamCampaignMonitoring',
      request,
      metadata || {},
      methodDescriptor_CampaignMonitoringService_StreamCampaignMonitoring);
};


module.exports = proto.monitoring;

